name: Ping Supabase

# Run this workflow on a schedule
on:
  schedule:
    - cron: "0 5 * * 7"  # Runs every sunday at 5 AM

    
  # Optionally, you can also run it manually with:
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Endpoint
        run: |
          # Ping the deployed Supabase function endpoint.
          # Replace the URL with your actual endpoint URL.
          curl -I https://glxyvjufrkqyynyxlpdo.supabase.co/functions/v1/ping

